### ISSUE TITLE
Inconsistency between the paper SI tables and the app

### ISSUE THREAD

**Issue by Ruibin-Liu** [lmboat/cysdb_app#1]
Hi,

Thanks for the great work in putting the Cys profiling data together. I am wondering whether you have updated version of the SI files for the Cys DB paper. I noticed a few problems with the table S1 data. For example, 273 rows are labeled as 'ligandable' ('yes' in the row) but no ligandable_datasets info is found for them. Also, for every row that 'ligandable_datasets' containds 'yang_wang', it also contains 'kuljanin_gygi', while in the app and paper Figure 1 they have different number of ligandable Cys residues. Finally, for some 'ligandable' residues in the table S1 data sheet, they are not so in the app. For example, 
'O15020_C115' is labeled as ligandable in the table S1 data sheet, but is not found for either the yang_wang or the kuljanin_gygi datasets. 

Could you help to fix them?

**Comment by lmboat** [comment]
Hi,

Thank you for reaching out and accessing CysDB, since our initial preprint release we have updated our SI Tables which are now available on ChemRxiv. Please check them out at https://chemrxiv.org/engage/chemrxiv/article-details/632e3d710e3c6a3b31266100!
